In [2]:
import torch as pt

This is the way to know the version of PyTorch 

In [3]:
print(pt.__version__)

2.0.1


At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array.

Let's create a tensor with a single number:

In [4]:
t1 = pt.tensor(4.)
print(t1)

tensor(4.)


In [5]:
print(t1.dtype)

torch.float32


In [7]:
t1 = pt.tensor(10)
print(t1)

tensor(10)


In [8]:
print(t1.dtype)

torch.int64


4. is a shorthand for 4.0. It is used to indicate to Python (and PyTorch) that you want to create a floating point number. We can verify this by checking the dtype attribute of our tensor:

# Let's Try Creating Complex Tensors

### Vectors

In [10]:
t2 = pt.tensor([1.,2,3,4]) # if any one of the element is in float, tensor will convert all the element of vector to floating point
print(t2.dtype)

torch.float32


In [11]:
t2 = pt.tensor([1,2,3,4])
print(t2.dtype)

torch.int64


### Matrix

In [21]:
t3 = pt.tensor([[5., 6], 
                [7, 8], 
                [9, 10]])  # if any one of the element is in float, it will convert all the element in float
print(t3.dtype)

torch.float32


In [20]:
t3 = pt.tensor([[5, 6], 
                [7, 8], 
                [9, 10]])
print(t3)
print(t3.dtype)

tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]])
torch.int64


### 3D Array

In [22]:
t4 = pt.tensor([[[11, 12, 13],
                 [13, 14, 15]],
                [[15, 16, 17],
                 [17, 18, 19.]]])
print(t4)

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


Tensors can have any number of dimensions, and different lengths along each dimension. We can inspect the length along each dimension using the .shape property of a tensor.

In [23]:
print(t1) # this have no dimension
print(t1.shape) # so, this will return empty list

tensor(10)
torch.Size([])


In [24]:
print(t2)
print(t2.shape) # this will return, one number, which implies the dimension is 1D

tensor([1, 2, 3, 4])
torch.Size([4])


In [28]:
print(t3)
print(t3.shape)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
torch.Size([3, 2])


In [29]:
print(t4)
print(t4.shape)

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])
torch.Size([2, 2, 3])


##### Tensor can only be form when the shape of the tensor is proper
t3 = pt.tensor([[5, 6, 7],</br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[7, 8], </br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[9, 10]])</br>
The above tensor is not in the proper shape, so it will give error

# Tensor operations and gradients
We can combine tensors with the usual arithmetic operations.</br>
Creating Tensor

In [34]:
x = pt.tensor(3.) 
# putting required_grad, indicates to torch, that this derivate is required or not
# keeping True indicates its required
w = pt.tensor(4., requires_grad=True) # required_grad is usefull to lower the computation's
b = pt.tensor(5., requires_grad=True)
print(x)
print(w)
print(b)

tensor(3.)
tensor(4., requires_grad=True)
tensor(5., requires_grad=True)


We've created 3 tensors x, w and b, all numbers. w and b have an additional parameter requires_grad set to True. We'll see what it does in just a moment.
</br>
Let's create a new tensor y by combining these tensors:

### Arithmetic operations

In [35]:
y = w * x + b
print(y)

tensor(17., grad_fn=<AddBackward0>)


As expected, y is a tensor with the value 3 * 4 + 5 = 17. </br>What makes PyTorch special is that we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. To compute the derivatives, we can call the .backward method on our result y.

### Complete derivation
Whenever the term comes gradient, then we talk about the derivatives of the vectors, matrix etc

In [37]:
y.backward()

The derivates of y w.r.t the input tensors are stored in the .grad property of the respective tensors.

### Display gradients

In [38]:
print('dy/dx:', x.grad) # this will come none, bcz we won't required the derivative w.r.t x
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


As expected, dy/dw has the same value as x i.e. 3, and dy/db has the value 1. Note that x.grad is None, because x doesn't have requires_grad set to True.
</br>
The "grad" in w.grad stands for gradient, which is another term for derivative, used mainly when dealing with matrices.

# Interoperability with Numpy
Instead of reinventing the wheel, PyTorch interoperates really well with Numpy to leverage its existing ecosystem of tools and libraries.



Here's how we create an array in Numpy:

In [39]:
import numpy as np

In [47]:
x = np.array([[1, 2], [3, 4.]])
print(x)

[[1. 2.]
 [3. 4.]]


We can convert a Numpy array to a PyTorch tensor using torch.from_numpy.

In [48]:
y = pt.from_numpy(x)
print(y)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


Let's verify that the numpy array and torch tensor have similar data types.

In [49]:
print(x.dtype)
print(y.dtype)

float64
torch.float64


We can convert a PyTorch tensor to a Numpy array using the .numpy method of a tensor.

In [51]:
z = y.numpy()
print(z)

[[1. 2.]
 [3. 4.]]


The interoperability between PyTorch and Numpy is really important because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.
</br>
You might wonder why we need the library like PyTorch at all since Numpy already provides data structures and utilities for working with multi-dimensional numeric data.
</br>
There are two reasons:</br>
1. <h6>AutoGrad</h6>: The ability to automatically compute gradients for tensors operations is essential for training deep learning models.
2. <h6>GPU support</h6>: While working with massive datasets and large models, PyTorch tensor operations can be performed effectively using a Graphic processing Unit(GPU). Computaion that might take typically take hours can be completed within minutes using GPUs

Learn About all Tensors operation here -> https://pytorch.org/docs/stable/tensors.html