In [1]:
import torch

Creating an empty tensor

In [7]:
x = torch.empty(2, 2) # we can also change the size of the tensor
print(x)

tensor([[-1.8891e+26,  6.0240e-01],
        [-3.8030e-22,  4.5916e-41]])


Giving random value to torch

In [8]:
x = torch.rand(2,2)
print(x)

tensor([[0.6379, 0.6933],
        [0.0998, 0.6639]])


Putting all the element of a tensor zero

In [10]:
x = torch.zeros(2,2) # or we can give ones -> torch.ones()
print(x)

tensor([[0., 0.],
        [0., 0.]])


Size of the Tensor

In [11]:
print(x.size()) # or x.shape

torch.Size([2, 2])


Creating Tensor using List

In [14]:
x = torch.tensor([2., 5,6,7])
print(x)

tensor([2., 5., 6., 7.])


# Basic Operations

In [20]:
x = torch.tensor([[1,2],[2,3]])
y = torch.tensor([[3,4],[4,5]])
print(x)
print(y)

tensor([[1, 2],
        [2, 3]])
tensor([[3, 4],
        [4, 5]])


In [21]:
z = x + y # or z = torch.add(x,y)
print(z)

tensor([[4, 6],
        [6, 8]])


Doing Inplace addition, In PyTorch every function having trailing underscore will do an inplace operation

In [22]:
y.add_(x) # This will modify our y
print(y)

tensor([[4, 6],
        [6, 8]])


Doing Subtraction

In [23]:
z = y - x # or z = y.sub(x)
print(z)

tensor([[3, 4],
        [4, 5]])


In [24]:
z = y.mul(x) # or z = y * x, this is just element wise multiplication, not matrix multiplication
print(z)

tensor([[ 4, 12],
        [12, 24]])


In [26]:
z = y/x # or z = ydiv(x), this is element wise
print(z)

tensor([[4.0000, 3.0000],
        [3.0000, 2.6667]])


# Slicing

In [30]:
x = torch.rand(5,5)
print(x)

tensor([[0.4335, 0.6474, 0.6831, 0.6054, 0.0666],
        [0.1050, 0.7575, 0.3705, 0.0443, 0.5511],
        [0.8438, 0.4435, 0.8251, 0.9463, 0.1316],
        [0.1135, 0.0518, 0.1334, 0.0564, 0.1663],
        [0.8233, 0.8688, 0.6076, 0.7740, 0.8695]])


In [31]:
print(x[:, 0])  # row, column

tensor([0.4335, 0.1050, 0.8438, 0.1135, 0.8233])


In [32]:
print(x[1,1].item()) # .tem() can only be used when there is one wlwmwnt in your tensor

0.7574676275253296


# Reshaping a tensor

In [33]:
x = torch.rand(4,4)
print(x)

tensor([[0.6930, 0.7063, 0.9233, 0.1914],
        [0.0132, 0.8703, 0.7623, 0.7324],
        [0.8222, 0.5025, 0.9727, 0.4824],
        [0.8974, 0.2841, 0.3176, 0.5745]])


In [36]:
print(x.view(16)) # create a 1D tensor of all the elements of ND tensor
# here in parameter we need to give all the element count. 4*4 -> 16

tensor([0.6930, 0.7063, 0.9233, 0.1914, 0.0132, 0.8703, 0.7623, 0.7324, 0.8222,
        0.5025, 0.9727, 0.4824, 0.8974, 0.2841, 0.3176, 0.5745])


In [37]:
# we can view the tensor in any dimesion, but number of element in the new dimension should be same
print(x.view(2,8))

tensor([[0.6930, 0.7063, 0.9233, 0.1914, 0.0132, 0.8703, 0.7623, 0.7324],
        [0.8222, 0.5025, 0.9727, 0.4824, 0.8974, 0.2841, 0.3176, 0.5745]])


# Converting Numpy To Tensor & vice-versa

In [38]:
import numpy as np

In [39]:
a = torch.ones(5)

from torch to numpy

In [45]:
q = a.numpy() # the address of q will be same as a, so any modification in a , reflects in q
print(q) 

[1. 1. 1. 1. 1.]


Form numpy to torch

In [43]:
b = np.ones(5) 
print(b)

[1. 1. 1. 1. 1.]


In [44]:
p = torch.from_numpy(b) # the address of p will be same as a, so any modification in b , reflects in p
print(p)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
