In [5]:
import torch

In [84]:
x = torch.tensor([1,2,3,4], dtype=torch.float32, requires_grad=True)
print(x)

tensor([1., 2., 3., 4.], requires_grad=True)


In [93]:
y = 2*x**2 + 3*x + 4
print(y)

tensor([ 8.9995, 17.9988, 30.9978, 47.9964], grad_fn=<AddBackward0>)


In [86]:
import numpy as np

In [87]:
l = [1,1,1,1]
v = np.array(l, dtype=np.float32)
print(v)

[1. 1. 1. 1.]


In [88]:
v = torch.from_numpy(v)
print(v)

tensor([1., 1., 1., 1.])


In [94]:
y.backward(v)

In [95]:
print(x.grad)

tensor([ 6.9997, 10.9996, 14.9994, 18.9992])


In [96]:
x.requires_grad_(False)
x -= x.grad*1e-5
x.grad.zero_()
x.requires_grad_(True)

tensor([0.9999, 1.9998, 2.9997, 3.9996], requires_grad=True)

In [92]:
print(x)

tensor([0.9999, 1.9999, 2.9999, 3.9998], requires_grad=True)
