In [1]:
from torchvision.datasets.utils import download_url

# Downloading The dataset

In [2]:
DATASET_URL = "https://gist.github.com/BirajCoder/5f068dfe759c1ea6bdfce9535acdb72d/raw/c84d84e3c80f93be67f6c069cbdc0195ec36acbd/insurance.csv"
DATA_FILENAME = "T05_Insurance.csv"
download_url(DATASET_URL, './dataset', DATA_FILENAME)

Using downloaded and verified file: ./dataset\T05_Insurance.csv


using pandas to read the dataset

In [3]:
import pandas as pd

Reading Dataset

In [4]:
dataset = pd.read_csv("dataset/T05_Insurance.csv")

In [5]:
dataset

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [6]:
dataset.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [7]:
len(dataset.columns)

7

In [8]:
len(dataset) # way to take out the number of rows

1338

In [9]:
type(dataset)

pandas.core.frame.DataFrame

In [10]:
dataset.info

<bound method DataFrame.info of       age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]>

In [11]:
dataset.describe

<bound method NDFrame.describe of       age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]>

In [12]:
dataset.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [13]:
# there is no use to know the region, as the insurance won't depened on region, it's depend on health
dataset.drop(["region"], axis=1, inplace=True)

In [14]:
dataset # now our main dataset got change, as we have used inplace=True while droping

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

One Hot Encoding For Cotegorical column

In [15]:
categorical_cols = ["sex", "smoker"]

In [16]:
output_cols = ["charges"]
input_cols = ["age", "sex", "bmi", "children", "smoker"]

In [17]:
def dataframe_to_arrays(dataframe):
    dataframe1 = dataframe.copy(deep=True)
    for col in categorical_cols: # this is ordinal encoding
        dataframe1[col] = dataframe1[col].astype('category').cat.codes
    inputs_array = dataframe1[input_cols].to_numpy()
    targets_array = dataframe1[output_cols].to_numpy()
    return inputs_array, targets_array
# doing ordinal encoding here, will not matter, bcz the categorical data we have is of two categories only

In [18]:
inputs_array, targets_array = dataframe_to_arrays(dataset)
inputs_array.shape, targets_array.shape

((1338, 5), (1338, 1))

In [19]:
inputs_array, targets_array

(array([[19.  ,  0.  , 27.9 ,  0.  ,  1.  ],
        [18.  ,  1.  , 33.77,  1.  ,  0.  ],
        [28.  ,  1.  , 33.  ,  3.  ,  0.  ],
        ...,
        [18.  ,  0.  , 36.85,  0.  ,  0.  ],
        [21.  ,  0.  , 25.8 ,  0.  ,  0.  ],
        [61.  ,  0.  , 29.07,  0.  ,  1.  ]]),
 array([[16884.924 ],
        [ 1725.5523],
        [ 4449.462 ],
        ...,
        [ 1629.8335],
        [ 2007.945 ],
        [29141.3603]]))

In [20]:
inputs_array.dtype, targets_array.dtype

(dtype('float64'), dtype('float64'))

In [21]:
type(inputs_array), type(targets_array)

(numpy.ndarray, numpy.ndarray)

In [22]:
def dataframe_to_arrays(dataframe):
    # Make a copy of the original dataframe
    dataframe1 = dataframe.copy(deep=True)
    # Convert non-numeric categorical columns to numbers
    for col in categorical_cols:
        dataframe1[col] = dataframe1[col].astype('category').cat.codes
    # Extract input & outupts as numpy arrays
    inputs_array = dataframe1[input_cols].to_numpy()
    targets_array = dataframe1[output_cols].to_numpy()
    return inputs_array, targets_array

In [23]:
inputs_array, targets_array = dataframe_to_arrays(dataset)
inputs_array, targets_array

(array([[19.  ,  0.  , 27.9 ,  0.  ,  1.  ],
        [18.  ,  1.  , 33.77,  1.  ,  0.  ],
        [28.  ,  1.  , 33.  ,  3.  ,  0.  ],
        ...,
        [18.  ,  0.  , 36.85,  0.  ,  0.  ],
        [21.  ,  0.  , 25.8 ,  0.  ,  0.  ],
        [61.  ,  0.  , 29.07,  0.  ,  1.  ]]),
 array([[16884.924 ],
        [ 1725.5523],
        [ 4449.462 ],
        ...,
        [ 1629.8335],
        [ 2007.945 ],
        [29141.3603]]))

In [24]:
import torch

In [25]:
inputs = torch.tensor(inputs_array)
targets = torch.tensor(targets_array)

In [26]:
inputs.dtype, targets.dtype

(torch.float64, torch.float64)

In [27]:
from torch.utils.data import DataLoader, TensorDataset, random_split

In [28]:
dataset = TensorDataset(inputs, targets)

In [29]:
train_ds, val_ds = random_split(dataset, [1200, 138])

In [30]:
batch_size = 15
train_loader = DataLoader(train_ds, batch_size, shuffle=True)
val_loader = DataLoader(val_ds, batch_size)

In [31]:
for xb, yb in train_loader:
    print("inputs:", xb)
    print("targets:", yb)
    break

inputs: tensor([[30.0000,  0.0000, 30.9000,  3.0000,  0.0000],
        [33.0000,  0.0000, 26.6950,  0.0000,  0.0000],
        [29.0000,  0.0000, 21.8500,  0.0000,  1.0000],
        [35.0000,  1.0000, 36.6700,  1.0000,  1.0000],
        [53.0000,  1.0000, 31.3500,  0.0000,  0.0000],
        [29.0000,  1.0000, 27.9400,  0.0000,  0.0000],
        [28.0000,  0.0000, 17.2900,  0.0000,  0.0000],
        [58.0000,  0.0000, 41.9100,  0.0000,  0.0000],
        [29.0000,  0.0000, 29.5900,  1.0000,  0.0000],
        [55.0000,  0.0000, 33.5350,  2.0000,  0.0000],
        [26.0000,  0.0000, 19.8000,  1.0000,  0.0000],
        [49.0000,  1.0000, 25.8400,  2.0000,  1.0000],
        [45.0000,  1.0000, 27.5000,  3.0000,  0.0000],
        [64.0000,  0.0000, 32.9650,  0.0000,  0.0000],
        [64.0000,  0.0000, 31.3000,  2.0000,  1.0000]], dtype=torch.float64)
targets: tensor([[ 5325.6510],
        [ 4571.4131],
        [16115.3045],
        [39774.2763],
        [27346.0421],
        [ 2867.1196],
    

# Model

Importing linear function to train the model

In [32]:
import torch.nn as nn
import torch.nn.functional as F

In [33]:
torch.set_default_dtype(torch.float64)

In [34]:
# instead of using mse loss, we are using rms loss, its bcz to find the local minima of gradient descent of mse loss is
# a difficult task. Using mse loss make the loss fluctuate about a point, loss will not get dcrease
class InsuranceModel(nn.Module):
    
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(5, 1)
        self.history = []
    
    def prediction(self, inputs):
        return self.linear(inputs)
    
    def lossCal(self, batch):
        inputs, targets = batch
        pred = self.prediction(inputs)
        mse = F.mse_loss(pred, targets)
        loss = torch.sqrt(mse)
#         losslist.append(loss.item()) # this is used to add loss in a list, to plot the loss graph
#         loss = F.l1_loss(pred, targets)
        return loss
    
    def validation_step(self, batch): # this will be given at validation phase.
        inputs, targets = batch
        loss = self.lossCal(batch)
        return {'val_loss': loss.detach()}
    
    def validation_epoch_end(self, outputs):
        batch_losses = [x['val_loss'] for x in outputs]
        epoch_loss = torch.stack(batch_losses).mean()   # Combine losses
        return {'val_loss': epoch_loss.item()}
    
    def evaluate(self, val_loader):
        outputs = [self.validation_step(batch) for batch in val_loader]
        return self.validation_epoch_end(outputs)
    
    def epoch_end(self, epoch, result):
        print("Epoch [{}], val_loss: {:.4f}".format(epoch, result['val_loss']))
        
    
    def training_(self, epochs, lr, train_loader, val_loader, opt_func=torch.optim.SGD):
        optimizer = opt_func(self.linear.parameters(), lr)
        
        for epoch in range(epochs):
            
            # training phase
            for batch in train_loader:
                loss = self.lossCal(batch)
                loss.backward()
                optimizer.step()
                optimizer.zero_grad()
                
            
            # validation phase
            result = self.evaluate(val_loader)
            self.epoch_end(epoch, result)
            self.history.append(result)
        
#         return self.history     

In [35]:
model = InsuranceModel()

In [36]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.4403,  0.0330,  0.3729,  0.1580,  0.1546]], requires_grad=True),
 Parameter containing:
 tensor([-0.3834], requires_grad=True)]

In [37]:
model.training_(650, 1, train_loader, val_loader)

Epoch [0], val_loss: 13245.0779
Epoch [1], val_loss: 13366.9315
Epoch [2], val_loss: 13488.0801
Epoch [3], val_loss: 13430.5541
Epoch [4], val_loss: 13162.4338
Epoch [5], val_loss: 13362.8523
Epoch [6], val_loss: 13613.5186
Epoch [7], val_loss: 13483.6953
Epoch [8], val_loss: 13448.7539
Epoch [9], val_loss: 13153.9904
Epoch [10], val_loss: 13132.9497
Epoch [11], val_loss: 13283.2450
Epoch [12], val_loss: 13279.2728
Epoch [13], val_loss: 13743.9071
Epoch [14], val_loss: 13116.0978
Epoch [15], val_loss: 13149.4132
Epoch [16], val_loss: 13053.2717
Epoch [17], val_loss: 13055.8916
Epoch [18], val_loss: 13280.5718
Epoch [19], val_loss: 13430.1532
Epoch [20], val_loss: 13026.6002
Epoch [21], val_loss: 13052.7490
Epoch [22], val_loss: 13173.3155
Epoch [23], val_loss: 13089.2434
Epoch [24], val_loss: 13075.2081
Epoch [25], val_loss: 13364.6291
Epoch [26], val_loss: 13153.7490
Epoch [27], val_loss: 13048.7185
Epoch [28], val_loss: 13017.7743
Epoch [29], val_loss: 13019.1875
Epoch [30], val_loss

Epoch [245], val_loss: 11093.6151
Epoch [246], val_loss: 11059.5900
Epoch [247], val_loss: 11096.4731
Epoch [248], val_loss: 11043.7996
Epoch [249], val_loss: 11039.3431
Epoch [250], val_loss: 11034.0249
Epoch [251], val_loss: 11479.7640
Epoch [252], val_loss: 10905.2182
Epoch [253], val_loss: 11337.4844
Epoch [254], val_loss: 11147.8524
Epoch [255], val_loss: 10977.9441
Epoch [256], val_loss: 10877.7382
Epoch [257], val_loss: 11671.1052
Epoch [258], val_loss: 11055.0424
Epoch [259], val_loss: 10946.6120
Epoch [260], val_loss: 10971.5736
Epoch [261], val_loss: 10971.1269
Epoch [262], val_loss: 10880.9794
Epoch [263], val_loss: 11064.4772
Epoch [264], val_loss: 10819.5572
Epoch [265], val_loss: 10803.1322
Epoch [266], val_loss: 11444.8991
Epoch [267], val_loss: 10784.2492
Epoch [268], val_loss: 10831.6040
Epoch [269], val_loss: 10943.5566
Epoch [270], val_loss: 10875.8838
Epoch [271], val_loss: 11584.7280
Epoch [272], val_loss: 10790.5086
Epoch [273], val_loss: 11155.4643
Epoch [274], v

Epoch [489], val_loss: 9768.4043
Epoch [490], val_loss: 9269.9269
Epoch [491], val_loss: 9214.1574
Epoch [492], val_loss: 9301.8548
Epoch [493], val_loss: 9351.4600
Epoch [494], val_loss: 9495.0837
Epoch [495], val_loss: 9327.8991
Epoch [496], val_loss: 9311.6255
Epoch [497], val_loss: 9266.8765
Epoch [498], val_loss: 9634.1670
Epoch [499], val_loss: 9187.9700
Epoch [500], val_loss: 9400.5766
Epoch [501], val_loss: 9195.5034
Epoch [502], val_loss: 9179.6932
Epoch [503], val_loss: 9325.1304
Epoch [504], val_loss: 9516.2570
Epoch [505], val_loss: 9210.2450
Epoch [506], val_loss: 9240.2714
Epoch [507], val_loss: 9134.7598
Epoch [508], val_loss: 9287.3514
Epoch [509], val_loss: 9327.6464
Epoch [510], val_loss: 9633.5975
Epoch [511], val_loss: 9201.1973
Epoch [512], val_loss: 9527.2616
Epoch [513], val_loss: 9171.6223
Epoch [514], val_loss: 9912.6066
Epoch [515], val_loss: 9132.6830
Epoch [516], val_loss: 9218.3547
Epoch [517], val_loss: 9099.5385
Epoch [518], val_loss: 9307.0203
Epoch [519

In [38]:
model.training_(250, 0.001, train_loader, val_loader)

Epoch [0], val_loss: 8866.6191
Epoch [1], val_loss: 8850.8699
Epoch [2], val_loss: 8838.0280
Epoch [3], val_loss: 8825.5098
Epoch [4], val_loss: 8813.6070
Epoch [5], val_loss: 8800.9749
Epoch [6], val_loss: 8789.8718
Epoch [7], val_loss: 8778.6382
Epoch [8], val_loss: 8766.6960
Epoch [9], val_loss: 8756.6818
Epoch [10], val_loss: 8746.3934
Epoch [11], val_loss: 8737.3832
Epoch [12], val_loss: 8729.6268
Epoch [13], val_loss: 8720.4361
Epoch [14], val_loss: 8712.7721
Epoch [15], val_loss: 8704.9606
Epoch [16], val_loss: 8698.3178
Epoch [17], val_loss: 8691.1761
Epoch [18], val_loss: 8685.2966
Epoch [19], val_loss: 8678.7794
Epoch [20], val_loss: 8672.5104
Epoch [21], val_loss: 8665.3377
Epoch [22], val_loss: 8659.7957
Epoch [23], val_loss: 8654.5841
Epoch [24], val_loss: 8646.8958
Epoch [25], val_loss: 8642.0398
Epoch [26], val_loss: 8637.3353
Epoch [27], val_loss: 8631.9758
Epoch [28], val_loss: 8627.9015
Epoch [29], val_loss: 8623.2171
Epoch [30], val_loss: 8619.2292
Epoch [31], val_lo

In [43]:
model.training_(250, 0.1, train_loader, val_loader)

Epoch [0], val_loss: 6635.9331
Epoch [1], val_loss: 6575.2905
Epoch [2], val_loss: 6629.4360
Epoch [3], val_loss: 6657.7908
Epoch [4], val_loss: 6643.1545
Epoch [5], val_loss: 6626.3908
Epoch [6], val_loss: 6643.9714
Epoch [7], val_loss: 6667.7315
Epoch [8], val_loss: 6632.1546
Epoch [9], val_loss: 6637.7317
Epoch [10], val_loss: 6686.5109
Epoch [11], val_loss: 6663.1394
Epoch [12], val_loss: 6678.6569
Epoch [13], val_loss: 6644.7219
Epoch [14], val_loss: 6666.5429
Epoch [15], val_loss: 6627.2403
Epoch [16], val_loss: 6628.3897
Epoch [17], val_loss: 6662.4133
Epoch [18], val_loss: 6645.8710
Epoch [19], val_loss: 6598.8474
Epoch [20], val_loss: 6589.3222
Epoch [21], val_loss: 6586.0860
Epoch [22], val_loss: 6601.1159
Epoch [23], val_loss: 6570.7741
Epoch [24], val_loss: 6641.9251
Epoch [25], val_loss: 6649.5445
Epoch [26], val_loss: 6603.0415
Epoch [27], val_loss: 6603.8040
Epoch [28], val_loss: 6636.4440
Epoch [29], val_loss: 6603.0323
Epoch [30], val_loss: 6656.0093
Epoch [31], val_lo

In [58]:
def predict_single(inputs, target, model):
    print(inputs)
    print(type(inputs))
    pred = model.prediction(inputs)
    return [pred, target]

In [53]:
for i in range(len(val_ds)):
    print(predict_single(val_ds[i][0], val_ds[i][1], model))

[tensor([31581.6337], grad_fn=<AddBackward0>), tensor([42111.6647])]
[tensor([14989.0734], grad_fn=<AddBackward0>), tensor([14418.2804])]
[tensor([6091.1081], grad_fn=<AddBackward0>), tensor([5116.5004])]
[tensor([10416.0277], grad_fn=<AddBackward0>), tensor([8334.5896])]
[tensor([10589.3001], grad_fn=<AddBackward0>), tensor([8988.1588])]
[tensor([13422.6748], grad_fn=<AddBackward0>), tensor([11566.3005])]
[tensor([7735.0147], grad_fn=<AddBackward0>), tensor([20420.6047])]
[tensor([11816.0349], grad_fn=<AddBackward0>), tensor([9144.5650])]
[tensor([28082.2301], grad_fn=<AddBackward0>), tensor([39611.7577])]
[tensor([13127.1798], grad_fn=<AddBackward0>), tensor([10602.3850])]
[tensor([23838.3633], grad_fn=<AddBackward0>), tensor([14283.4594])]
[tensor([11842.7256], grad_fn=<AddBackward0>), tensor([22192.4371])]
[tensor([6930.3480], grad_fn=<AddBackward0>), tensor([4357.0436])]
[tensor([27543.9516], grad_fn=<AddBackward0>), tensor([18765.8754])]
[tensor([28994.9048], grad_fn=<AddBackward

In [59]:
predict_single(val_ds[0][0], val_ds[0][1], model)

tensor([46.0000,  0.0000, 35.5300,  0.0000,  1.0000])
<class 'torch.Tensor'>


[tensor([31581.6337], grad_fn=<AddBackward0>), tensor([42111.6647])]

In [60]:
lis = [54, 1, 34, 2, 1]

In [61]:
def predict_unknown(inputs, model):
    pred = model.prediction(inputs)
    return pred

In [67]:
int(predict_unknown(torch.tensor(lis, dtype=torch.float64), model).item())

33417

In [68]:
torch.save(model.state_dict(), 'SavedModel/T05_HealthInsuranceCostPrediction.pth')

In [70]:
import pickle # we can save our model using pickle also

In [88]:
pickle.dump(model.linear, open('SavedModel/T05_InsuranceModel.pkl', 'wb'))

In [76]:
list(model.linear.parameters())

[Parameter containing:
 tensor([[  213.8172,  -272.6502,   126.6323,   295.7170, 20924.0113]],
        requires_grad=True),
 Parameter containing:
 tensor([-3677.2120], requires_grad=True)]

In [77]:
model.state_dict()

OrderedDict([('linear.weight',
              tensor([[  213.8172,  -272.6502,   126.6323,   295.7170, 20924.0113]])),
             ('linear.bias', tensor([-3677.2120]))])

In [84]:
model.predict(torch.tensor([33.0000,  0.0000, 26.6950,  0.0000,  0.0000]))

AttributeError: 'InsuranceModel' object has no attribute 'predict'

In [87]:
model

InsuranceModel(
  (linear): Linear(in_features=5, out_features=1, bias=True)
)