# Logistic Regression
- This can used as regression and classification
- when we apply logistic on tabular data then its called regression
- when we apply logistic on raw data the its called classification

In [1]:
import torch
import torch.nn as nn
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [2]:
dir(datasets)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_arff_parser',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_boston',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_circl

# Preparing Data

In [3]:
# Here its a binary classfication problem
bc = datasets.load_breast_cancer()

In [4]:
print(bc['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [5]:
# creating Dataframe of dataset
df_cancer = pd.DataFrame(np.c_[bc['data'], bc['target']], columns= np.append(bc['feature_names'],['target']))

In [6]:
# printing some value sof dataframe
df_cancer.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890     0.0  
1          0.2750                  0.08902     0.0  
2          0.3613                  0.08758     0.0  
3          0.6638                  0.17300     0.0  
4          0.2364                  0.07678     0.0  

[5 rows x 31 columns]

In [7]:
df_cancer['target'].value_counts()
# 0 -> Mailgnant, 1-> Benign

1.0    357
0.0    212
Name: target, dtype: int64

In [8]:
len(df_cancer)

569

In [9]:
x = df_cancer.iloc[:,:-1].values

In [10]:
y = df_cancer.iloc[:,[-1]].values

In [11]:
x, y

(array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.

In [12]:
x.shape, y.shape

((569, 30), (569, 1))

In [13]:
x.dtype, y.dtype

(dtype('float64'), dtype('float64'))

# Train Test Split

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.095, random_state=1106)

In [16]:
# scaling the data, this is always recommended to do when we do logistic regression
sc = StandardScaler()

In [17]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [18]:
x_train, x_test

(array([[ 1.95710871,  1.66320291,  2.06940899, ...,  2.6580549 ,
          1.92165439,  2.39897742],
        [-0.97517357, -0.98282241, -0.99919145, ..., -1.74239044,
         -0.30725663, -1.22492919],
        [ 0.59639478,  0.02739391,  0.7270748 , ...,  0.94820222,
          0.66909632,  0.38834978],
        ...,
        [ 0.56265808, -0.35027871,  0.61283359, ...,  1.08311081,
          2.1978595 ,  2.12213614],
        [ 1.97678846,  0.84529841,  1.84500662, ...,  1.3029057 ,
         -0.12740214, -0.48560013],
        [ 1.15023909, -0.12089473,  1.09019864, ...,  0.94971804,
         -0.14346058, -0.12082104]]),
 array([[ 0.53173276,  0.89163861,  0.43739174, ..., -0.23035316,
          0.07493416,  0.01705678],
        [-0.10645332,  1.01444013, -0.14034237, ..., -0.81682656,
         -0.38273128, -1.1397055 ],
        [ 1.8137277 ,  0.63676752,  1.74300554, ...,  1.16799711,
          0.01230626, -1.38723418],
        ...,
        [-1.32800332,  0.53481908, -1.32110686, ..., -

In [19]:
# Converting x_train to torch tensor
x_train = torch.from_numpy(x_train.astype(np.float32))
y_train = torch.from_numpy(y_train.astype(np.int64))
x_test = torch.from_numpy(x_test.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.int64))

In [20]:
y_train.shape, y_test.shape

(torch.Size([514, 1]), torch.Size([55, 1]))

In [21]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

(torch.Size([514, 30]),
 torch.Size([514, 1]),
 torch.Size([55, 30]),
 torch.Size([55, 1]))

In [22]:
x_train.dtype, y_train.dtype, x_test.dtype, y_test.dtype

(torch.float32, torch.int64, torch.float32, torch.int64)

# Defining DataLoader

In [23]:
from torch.utils.data import DataLoader, TensorDataset, random_split

In [24]:
dataset = TensorDataset(x_train, y_train)

In [25]:
len(dataset)

514

In [26]:
type(dataset[0])

tuple

In [27]:
dataset[0][1].dtype

torch.int64

In [28]:
train_ds, val_ds = random_split(dataset, [400, 114])

In [29]:
len(train_ds), len(val_ds)

(400, 114)

In [30]:
batch_size = 25
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
val_dl = DataLoader(val_ds, batch_size)

In [31]:
len(train_dl), len(val_dl)

(16, 5)

# Building Model

In [32]:
import torch.nn.functional as F

In [33]:
from tqdm import trange

In [89]:
class LogisticRegression(nn.Module):

    def __init__(self, inputs):
        super().__init__()
        self.linear = nn.Linear(inputs, 2)
        self.history=[]

    def prediction(self, inputs): 
        return self.linear(inputs) # we will apply sigmoid fuction as we have binary classification

    def lossCal(self, batch):
        inputs, targets = batch
        preds = self.prediction(inputs)
        loss = F.cross_entropy(preds, torch.reshape(targets, (len(targets), )))
        return preds, loss, targets

    def accuracy(self, outputs, labels):
        _, preds = torch.max(outputs, dim=1)        
        return torch.tensor(torch.sum(preds == torch.reshape(labels, (len(labels), ))).item()/len(preds))

    def validation_step(self, batch):
        # inputs, targets = batch
        # targets = torch.reshape(targets, (len(targets), ))
        # preds = self.prediction(inputs)
        preds, loss, targets = self.lossCal(batch)
        acc = self.accuracy(preds, targets)
        return {'val_loss':loss, 'val_acc':acc}

    def validation_epoch_end(self, outputs):
        batch_losses = [x['val_loss'] for x in outputs]
        epoch_loss = torch.stack(batch_losses).mean()
        batch_acc = [x['val_acc'] for x in outputs]
        epoch_acc = torch.stack(batch_acc).mean()
        return {'val_loss':epoch_loss.item(), 'val_acc':epoch_acc.item()}
        

    def evaluate(self, val_dl):
        outputs = [self.validation_step(batch) for batch in val_dl]
        return self.validation_epoch_end(outputs)

    def epoch_end(self, epoch, result):
        print("Epoch [{}], val_loss: {:.4f}, val_acc: {:.4f}".format(epoch, result['val_loss'], result['val_acc']))

    def model_training(self, epochs, lr, train_dl, val_dl, opt_fun=torch.optim.SGD):
        optimizer = opt_fun(self.linear.parameters(), lr)
        
        for epoch in trange(epochs):
            for batch in train_dl:
                _, loss, _=self.lossCal(batch)
                loss.backward()
                optimizer.step()
                optimizer.zero_grad()
                
            result = self.evaluate(val_dl)
            if(epoch%10 == 0):
                self.epoch_end(epoch, result)
            self.history.append(result)

    def prediction_compare(self, input, target):
        return self.model_prediction(input) == target

    def model_prediction(self, input):
        pred = self.prediction(input)
        _, index = torch.max(pred, dim=1)
        return index

In [90]:
model = LogisticRegression(30)

In [91]:
list(model.linear.parameters())

[Parameter containing:
 tensor([[-0.0443, -0.1569,  0.0047,  0.1717,  0.0573,  0.1101,  0.0597,  0.0559,
          -0.1566,  0.1814, -0.0300,  0.1288,  0.0525,  0.1570,  0.0575, -0.1064,
          -0.0079,  0.1819, -0.0831, -0.1406, -0.1188, -0.0369, -0.1426, -0.1036,
          -0.1595, -0.1220,  0.1318,  0.0749, -0.0559, -0.1142],
         [ 0.1626,  0.1662, -0.1603, -0.0063, -0.0585, -0.1244, -0.0690,  0.0324,
           0.1780,  0.1734, -0.1362,  0.1788,  0.0544, -0.1417, -0.1034,  0.1334,
          -0.1814, -0.0613,  0.1779,  0.0914, -0.1380, -0.0637, -0.1591, -0.0965,
           0.1307,  0.0832, -0.0930, -0.0776,  0.0269,  0.0699]],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.1546, -0.1300], requires_grad=True)]

In [92]:
# checking loss and accuracy at random weights
model.evaluate(val_dl)

{'val_loss': 0.7777682542800903, 'val_acc': 0.5479999780654907}

In [93]:
model.model_training(21, 0.001, train_dl, val_dl)

 10%|███████▉                                                                           | 2/21 [00:00<00:01,  9.66it/s]

Epoch [0], val_loss: 0.7335, val_acc: 0.5720


 67%|██████████████████████████████████████████████████████▋                           | 14/21 [00:01<00:00, 13.11it/s]

Epoch [10], val_loss: 0.4773, val_acc: 0.7954


100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 11.35it/s]

Epoch [20], val_loss: 0.3666, val_acc: 0.8657


In [94]:
model.model_training(21, 0.001, train_dl, val_dl)

  5%|███▉                                                                               | 1/21 [00:00<00:02,  9.97it/s]

Epoch [0], val_loss: 0.3590, val_acc: 0.8657


 62%|██████████████████████████████████████████████████▊                               | 13/21 [00:01<00:00, 12.56it/s]

Epoch [10], val_loss: 0.3014, val_acc: 0.8960


100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:02<00:00, 10.37it/s]

Epoch [20], val_loss: 0.2647, val_acc: 0.9200


In [95]:
model.model_training(21, 0.001, train_dl, val_dl)

  0%|                                                                                           | 0/21 [00:00<?, ?it/s]

Epoch [0], val_loss: 0.2617, val_acc: 0.9200


 67%|██████████████████████████████████████████████████████▋                           | 14/21 [00:01<00:00, 13.83it/s]

Epoch [10], val_loss: 0.2370, val_acc: 0.9360


100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 12.34it/s]

Epoch [20], val_loss: 0.2186, val_acc: 0.9440


In [96]:
model.model_training(21, 0.001, train_dl, val_dl)

 10%|███████▉                                                                           | 2/21 [00:00<00:02,  6.87it/s]

Epoch [0], val_loss: 0.2170, val_acc: 0.9440


 57%|██████████████████████████████████████████████▊                                   | 12/21 [00:01<00:00,  9.54it/s]

Epoch [10], val_loss: 0.2031, val_acc: 0.9520


100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:02<00:00,  9.93it/s]

Epoch [20], val_loss: 0.1919, val_acc: 0.9600


In [97]:
model.model_training(21, 0.001, train_dl, val_dl)

  5%|███▉                                                                               | 1/21 [00:00<00:02,  7.13it/s]

Epoch [0], val_loss: 0.1909, val_acc: 0.9600


 62%|██████████████████████████████████████████████████▊                               | 13/21 [00:01<00:00,  9.28it/s]

Epoch [10], val_loss: 0.1818, val_acc: 0.9680


100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 10.52it/s]

Epoch [20], val_loss: 0.1742, val_acc: 0.9680


In [98]:
model.model_training(21, 0.001, train_dl, val_dl)

  5%|███▉                                                                               | 1/21 [00:00<00:04,  4.31it/s]

Epoch [0], val_loss: 0.1735, val_acc: 0.9680


 57%|██████████████████████████████████████████████▊                                   | 12/21 [00:01<00:00,  9.71it/s]

Epoch [10], val_loss: 0.1670, val_acc: 0.9680


100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:02<00:00,  7.72it/s]

Epoch [20], val_loss: 0.1615, val_acc: 0.9760


In [99]:
model.model_training(21, 0.001, train_dl, val_dl)

 10%|███████▉                                                                           | 2/21 [00:00<00:02,  8.20it/s]

Epoch [0], val_loss: 0.1610, val_acc: 0.9760


 57%|██████████████████████████████████████████████▊                                   | 12/21 [00:01<00:00, 11.04it/s]

Epoch [10], val_loss: 0.1561, val_acc: 0.9760


100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:02<00:00, 10.15it/s]

Epoch [20], val_loss: 0.1519, val_acc: 0.9760


In [100]:
model.model_training(21, 0.001, train_dl, val_dl)

  5%|███▉                                                                               | 1/21 [00:00<00:03,  5.34it/s]

Epoch [0], val_loss: 0.1515, val_acc: 0.9760


 52%|██████████████████████████████████████████▉                                       | 11/21 [00:01<00:00, 10.80it/s]

Epoch [10], val_loss: 0.1478, val_acc: 0.9760


100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:02<00:00,  9.78it/s]

Epoch [20], val_loss: 0.1444, val_acc: 0.9760


In [101]:
model.model_training(21, 0.001, train_dl, val_dl)

  0%|                                                                                           | 0/21 [00:00<?, ?it/s]

Epoch [0], val_loss: 0.1441, val_acc: 0.9760

 10%|███████▉                                                                           | 2/21 [00:00<00:02,  8.20it/s]

 62%|██████████████████████████████████████████████████▊                               | 13/21 [00:01<00:00, 13.12it/s]

Epoch [10], val_loss: 0.1411, val_acc: 0.9760


100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:02<00:00, 10.30it/s]

Epoch [20], val_loss: 0.1384, val_acc: 0.9760


In [102]:
model.model_training(21, 0.001, train_dl, val_dl)

  5%|███▉                                                                               | 1/21 [00:00<00:02,  9.97it/s]

Epoch [0], val_loss: 0.1381, val_acc: 0.9760


 57%|██████████████████████████████████████████████▊                                   | 12/21 [00:01<00:00, 16.47it/s]

Epoch [10], val_loss: 0.1357, val_acc: 0.9760


100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 12.55it/s]

Epoch [20], val_loss: 0.1335, val_acc: 0.9760


In [103]:
x_test[0]

tensor([ 0.5317,  0.8916,  0.4374,  0.3986, -1.0150, -0.7173, -0.7039, -0.4086,
        -1.0394, -0.8218, -0.0926, -0.0553, -0.1948,  0.0027, -0.9924, -0.9069,
        -0.6793, -0.6858, -0.7156, -0.2864,  0.5946,  1.2983,  0.4887,  0.4607,
        -0.6259, -0.6337, -0.6094, -0.2304,  0.0749,  0.0171])

In [104]:
x_test.dtype

torch.float32

In [105]:
x_test[0].shape

torch.Size([30])

In [106]:
model.model_prediction(torch.reshape(x_test[0], (1, len(x_test[0]))))

tensor([0])

In [107]:
y_test[0]

tensor([0])

In [108]:
model.prediction_compare(torch.reshape(x_test[5], (1, len(x_test[5]))), y_test[5])

tensor([True])

In [109]:
model.history

[{'val_loss': 0.7334951162338257, 'val_acc': 0.5720000267028809},
 {'val_loss': 0.6942923665046692, 'val_acc': 0.6485714316368103},
 {'val_loss': 0.6593180298805237, 'val_acc': 0.680571436882019},
 {'val_loss': 0.6280192136764526, 'val_acc': 0.7108571529388428},
 {'val_loss': 0.599864661693573, 'val_acc': 0.7411428689956665},
 {'val_loss': 0.5743957757949829, 'val_acc': 0.7491428256034851},
 {'val_loss': 0.5513492822647095, 'val_acc': 0.7571428418159485},
 {'val_loss': 0.5303345322608948, 'val_acc': 0.7571428418159485},
 {'val_loss': 0.5111194849014282, 'val_acc': 0.7651427984237671},
 {'val_loss': 0.49351996183395386, 'val_acc': 0.7731428146362305},
 {'val_loss': 0.4773048460483551, 'val_acc': 0.7954285740852356},
 {'val_loss': 0.4623526930809021, 'val_acc': 0.8257142901420593},
 {'val_loss': 0.44851118326187134, 'val_acc': 0.8257142901420593},
 {'val_loss': 0.43567800521850586, 'val_acc': 0.8257142901420593},
 {'val_loss': 0.42372044920921326, 'val_acc': 0.8417142629623413},
 {'val_l

In [111]:
# Saving The Model
torch.save(model.state_dict(), 'SavedModel/T14_LogisticRegression.pth')